name: flaarum # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '1.0.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: A database that enforces structures # 79 char long summary
description: |
  Flaarum brings in autoindexing, table expansion ( a more comfortable form of 
  joins), and supports any change to its table structure.

  It also supports a query language though not SQL.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  store:
    # See 'snapcraft plugins'
    plugin: dump
    source: ./artifacts/flaarum.tar.xz
    source-type: tar
    organize:
      flaarum.json: /etc/flaarum.json

plugs:
  data-things:
    interface: system-files
    read:
      - /etc/flaarum.json
      - /etc/flaarum.keyfile
    write:
      - /flaarumd

apps:
  store:
    command: store
    daemon: simple
    restart-condition: on-abnormal
    plugs:
      - network
      - network-bind
      - data-things

  mkpass:
    command: mkpass
    plugs:
      - data-things
